#!/usr/bin/env bash
# this code prings the story
while read line
do
	USERNAME=$(echo "$line" | cut -d: -f1)
	GROUP_ID=$(echo "$line" | cut -d: -f4)
	HOME_DIRECTORY=$(echo "$line" | cut -d: -f6)
	COMMAND/SHELL=$(echo "$line" | cut -d: -f7)
	USER_ID=$(echo "$line" | cut -d: -f3)
	PASSWORD=$(echo "$line" | cut -d: -f2)
	USER_ID_INFO=$(echo "$line" | cut -d: -f5)
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
