#!/usr/bin/env bash
# Script that groups Apache log data by IP and status code

awk '{print $1, $9}' apache-access.log \
  | awk '{c[$0]++} END {for (k in c) printf "%5d %s\n", c[k], k}' \
  | sort -nr
