#!/usr/bin/env bash
#A script that: Prints To infinity and beyond indefinitely Sleeps 2 seconds each loop On SIGTERM, printsœI am invincible
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
